server:
  port: 8081
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
##通用mapper配置
#mapper:
##公用接口类路径
#  mappers: com.example.demo.baseMapper.IBaseDao
#  identity: MYSQL